Feature/consumption analysis prefix
rl-institut/bd_app pull request #41
Opened 2024-12-16 14:57 UTC by josihoppe

made multiple consumption inputs possible with prefix

2025-01-07 09:33 UTC, henhuy requested changes
It works and looks good, but there is a bug in the code which should be checked.
It seems like one function is not used at all - maybe it can be removed, maybe it must be fixed.. Please check. I will fix merge conflict

2025-01-07 09:33 UTC, henhuy commented on building_dialouge_webapp/heat/views.py
> +            year_id += 1
Does not have a return statement, thus always returns None.
Strangely, everything works though - maybe this is not needed? Could you check your logic below and maybe rewrite or fix this?

2025-01-08 13:01 UTC, josihoppe commented on building_dialouge_webapp/heat/views.py
> +            year_id += 1
hm, it seems I forgot the return statement. I think i wanted to use that existing_years function to get all the instances that were created. But the way I used it, it doesn't make sense. 
It might be used though, when no year is given e.g. when you come from the intro page, to either open the last instance (the one at the end of the array) or even open the next "free slot" so a new year can be build. Not sure which behaviour is preferenced.

2025-01-08 13:07 UTC, henhuy commented on building_dialouge_webapp/heat/views.py
> +            year_id += 1
I think we can remove the function and use next free slot if no year is given

2025-01-08 13:09 UTC, josihoppe commented on building_dialouge_webapp/heat/views.py
> +            year_id += 1
Alrighty, will do it like that :D

2025-01-09 08:10 UTC, henhuy approved these changes

2025-01-09 08:10 UTC, merged